/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorCatpresentacion;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author Jnatn'h
 */
public class CatPresentacion extends java.awt.Dialog {
    
    private ControladorCatpresentacion controlador;
    
    public void setController(ControladorCatpresentacion controller){
        this.controlador = controller;
        this.asignarlistener();
    }
    public ControladorCatpresentacion getController(){
        return this.controlador;
    }
    public void asignarlistener(){
        Textbusqueda.addKeyListener(getController());
        Catpresentacion.addMouseListener(getController());
        nuevapresentacion.addActionListener(getController());
        salircat.addActionListener(getController());
    }
    public JTextField getTextbusqueda(){
        return Textbusqueda;
    }
    public void setTextBusqueda(JTextField Textbusqueda){
        this.Textbusqueda = Textbusqueda;
    }
    public JTable getCatpresentacion(){
        return Catpresentacion;
    }
    public void setCatpresentacion(JTable Catpresentacion){
        this.Catpresentacion = Catpresentacion;
    }
    public JLabel getLeyenda(){
        return Leyenda;
    }
    public void setLeyenda(JLabel Leyenda){
        this.Leyenda = Leyenda;
    }
    public JButton getNuevapresentacion(){
        return nuevapresentacion;
    }
    public void setNuevapresentacion(JButton nuevapresentacion){
        this.nuevapresentacion = nuevapresentacion;
    }
    public JButton getSalircat(){
        return salircat;
    }
    public void setSalircat(JButton salircat){
        this.salircat = salircat;
    }
    /**
     * Creates new form CatPresentacion
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
     */
    public CatPresentacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centraVentana();
        this.setTitle("Presentación");
        this.setResizable(false);
        setController(new ControladorCatpresentacion(this));
    }
    private void centraVentana() {
            //Obtiene el tamaño de la pantalla
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            // Obtiene el tamaño de la ventana de la aplicación
            Dimension frameSize = getSize();
            // Se asegura que el tamaño de la ventana de la aplicación
            // no exceda el tamaño de la pantalla
            if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
            }
            // Centra la ventana de la aplicación sobre la pantalla
            setLocation((screenSize.width - frameSize.width) / 2,
            (screenSize.height - frameSize.height) / 2);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new org.edisoncor.gui.panel.Panel();
        Textbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Catpresentacion = new javax.swing.JTable();
        salircat = new javax.swing.JButton();
        nuevapresentacion = new javax.swing.JButton();
        header = new org.edisoncor.gui.panel.Panel();
        Leyenda = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(471, 414));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
        cat.setMaximumSize(new java.awt.Dimension(471, 414));

        Textbusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextbusquedaFocusGained(evt);
            }
        });
        Textbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyTyped(evt);
            }
        });

        Catpresentacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Catpresentacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Presentacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Catpresentacion.setToolTipText("Presentación");
        Catpresentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Catpresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CatpresentacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CatpresentacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Catpresentacion);

        salircat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
        salircat.setText("Salir");
        salircat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nuevapresentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/registrar.png"))); // NOI18N
        nuevapresentacion.setText("Nuevo");
        nuevapresentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevapresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevapresentacionActionPerformed(evt);
            }
        });

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-presentaciones.png"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(471, 75));
        header.setPreferredSize(new java.awt.Dimension(471, 75));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Leyenda.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout catLayout = new javax.swing.GroupLayout(cat);
        cat.setLayout(catLayout);
        catLayout.setHorizontalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(catLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Textbusqueda)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(catLayout.createSequentialGroup()
                        .addComponent(nuevapresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(catLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        catLayout.setVerticalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Textbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevapresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(cat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TextbusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextbusquedaFocusGained
        String Leyend = "Buscar en el catálogo el registro de presentación... ";
        this.getLeyenda().setText(Leyend);
    }//GEN-LAST:event_TextbusquedaFocusGained

    private void TextbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TextbusquedaKeyReleased

    private void TextbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyTyped

    }//GEN-LAST:event_TextbusquedaKeyTyped

    private void CatpresentacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CatpresentacionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CatpresentacionKeyReleased

    private void CatpresentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CatpresentacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CatpresentacionKeyTyped

    private void nuevapresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevapresentacionActionPerformed

    }//GEN-LAST:event_nuevapresentacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Catpresentacion;
    private javax.swing.JLabel Leyenda;
    private javax.swing.JTextField Textbusqueda;
    private org.edisoncor.gui.panel.Panel cat;
    private org.edisoncor.gui.panel.Panel header;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton nuevapresentacion;
    private javax.swing.JButton salircat;
    // End of variables declaration//GEN-END:variables
}
