/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorCattiposervicios;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author Jnatn'h
 */
public class CatTiposervicios extends java.awt.Dialog {
    private ControladorCattiposervicios controlador;
    private void setController(ControladorCattiposervicios contr){
        this.controlador = contr;
        this.controlador.ListaTiposervicios();
        this.asginarListener();
    }
    public ControladorCattiposervicios getController(){
        return this.controlador;
    }
    private void asginarListener(){
        Textbusqueda.addKeyListener(getController());
        Cattiposervicios.addMouseListener(controlador);
        nuevotiposervicio.addActionListener(controlador);
        salircat.addActionListener(controlador);
    }
    public JTextField getTextbusqueda(){
        return Textbusqueda;
    }
    public void setTextBusqueda(JTextField Textbusqueda){
        this.Textbusqueda = Textbusqueda;
    }
    public JTable getCattiposervicios(){
        return Cattiposervicios;
    }
    public void setCattiposervicios(JTable Cattiposervicios){
        this.Cattiposervicios = Cattiposervicios;
    }   
    public JLabel getLeyenda(){
        return Leyenda;
    }
    public void setLeyenda(JLabel Leyenda){
        this.Leyenda = Leyenda;
    }
    public JButton getNuevotiposervicio(){
        return nuevotiposervicio;
    }
    public void setNuevotiposervicio(JButton nuevotiposervicio){
        this.nuevotiposervicio = nuevotiposervicio;
    }
    public JButton getSalircat(){
        return salircat;
    }
    public void setSalircat(JButton salircat){
        this.salircat = salircat;
    }
    /**
     * Creates new form CatTiposervicios
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
     */
    public CatTiposervicios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centraVentana();
        this.setTitle("Tipos de Servicios");
        this.setResizable(false);
       setController(new ControladorCattiposervicios(this));
    }
    private void centraVentana() {
        //Obtiene el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtiene el tamaño de la ventana de la aplicación
        Dimension frameSize = getSize();
        // Se asegura que el tamaño de la ventana de la aplicación
        // no exceda el tamaño de la pantalla
        if (frameSize.height > screenSize.height) {
        frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
        frameSize.width = screenSize.width;
        }
        // Centra la ventana de la aplicación sobre la pantalla
        setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
}
    private void validar(KeyEvent e){
    char b = e.getKeyChar();
         if(!Character.isLetter(b) &&  b != KeyEvent.VK_SPACE){
            e.consume();
            if( this.getTextbusqueda().getText().length() >= 30)
    {
        e.consume();
    } 
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new org.edisoncor.gui.panel.Panel();
        Textbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cattiposervicios = new javax.swing.JTable();
        salircat = new javax.swing.JButton();
        nuevotiposervicio = new javax.swing.JButton();
        panel2 = new org.edisoncor.gui.panel.Panel();
        Leyenda = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(480, 416));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
        cat.setMaximumSize(new java.awt.Dimension(480, 416));
        cat.setMinimumSize(new java.awt.Dimension(480, 416));

        Textbusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextbusquedaFocusGained(evt);
            }
        });
        Textbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyTyped(evt);
            }
        });

        Cattiposervicios.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Cattiposervicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tipo de Servicios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Cattiposervicios.setToolTipText("");
        Cattiposervicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cattiposervicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CattiposerviciosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CattiposerviciosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Cattiposervicios);

        salircat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
        salircat.setText("Salir");
        salircat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salircat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nuevotiposervicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/registrar.png"))); // NOI18N
        nuevotiposervicio.setText("Nuevo");
        nuevotiposervicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nuevotiposervicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevotiposervicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevotiposervicioActionPerformed(evt);
            }
        });

        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-tipodeservicios.png"))); // NOI18N
        panel2.setMaximumSize(new java.awt.Dimension(480, 75));
        panel2.setMinimumSize(new java.awt.Dimension(480, 75));
        panel2.setPreferredSize(new java.awt.Dimension(480, 75));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Leyenda.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout catLayout = new javax.swing.GroupLayout(cat);
        cat.setLayout(catLayout);
        catLayout.setHorizontalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(catLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Textbusqueda)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(catLayout.createSequentialGroup()
                        .addComponent(nuevotiposervicio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(catLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        catLayout.setVerticalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catLayout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Textbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevotiposervicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(cat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TextbusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextbusquedaFocusGained
        String Leyend = "Buscar en el catálogo el registro de tipos de servicios... ";
        this.getLeyenda().setText(Leyend);
    }//GEN-LAST:event_TextbusquedaFocusGained

    private void TextbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TextbusquedaKeyReleased

    private void TextbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyTyped
        this.validar(evt);
    }//GEN-LAST:event_TextbusquedaKeyTyped

    private void CattiposerviciosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CattiposerviciosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CattiposerviciosKeyReleased

    private void CattiposerviciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CattiposerviciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CattiposerviciosKeyTyped

    private void nuevotiposervicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevotiposervicioActionPerformed

    }//GEN-LAST:event_nuevotiposervicioActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Cattiposervicios;
    private javax.swing.JLabel Leyenda;
    private javax.swing.JTextField Textbusqueda;
    private org.edisoncor.gui.panel.Panel cat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevotiposervicio;
    private org.edisoncor.gui.panel.Panel panel2;
    private javax.swing.JButton salircat;
    // End of variables declaration//GEN-END:variables
}
