/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorCattipoorden;
import java.awt.Dimension;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JTable;
/**
 *
 * @author Jnatn'h
 */
public class cattiporden extends java.awt.Dialog {
    private ControladorCattipoorden controlador;
    private void setController(ControladorCattipoorden controlador){
        this.controlador = controlador;
        this.asignarListener();
        this.controlador.ListaTipoorden();
    }
    public ControladorCattipoorden getController(){
        return this.controlador;
    }
    public void asignarListener(){
        Textbusqueda.addKeyListener(getController());
        Cattipoorden.addMouseListener(controlador);
        nuevatipoorden.addActionListener(controlador);
        salircat.addActionListener(controlador);
    }
    public JTextField getTextbusqueda(){
        return Textbusqueda;
    }
    public void setTextBusqueda(JTextField Textbusqueda){
        this.Textbusqueda = Textbusqueda;
    }
    public JTable getCattipoorden(){
        return Cattipoorden;
    }
    public void setCattipoorden(JTable Cattipoorden){
        this.Cattipoorden = Cattipoorden;
    }  
    public JLabel getLeyenda(){
        return leyenda;
    }
    public void setLeyenda(JLabel Leyenda){
        this.leyenda = Leyenda;
    }
    public JButton getNuevatipoorden(){
        return nuevatipoorden;
    }
    public void setNuevatipoorden(JButton nuevatipoorden){
        this.nuevatipoorden = nuevatipoorden;
    }
    public JButton getSalircat(){
        return salircat;
    }
    public void setSalircat(JButton salircat){
        this.salircat = salircat;
    }
    
    /**
     * Creates new form cattiporden
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
     */
    public cattiporden(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centraVentana();
        this.setTitle("Tipos de ordenes");
        this.setResizable(false);
        setController(new ControladorCattipoorden(this));
    }
    private void validar (KeyEvent e){
        char b = e.getKeyChar();
         if(!Character.isLetter(b) &&  b != KeyEvent.VK_SPACE){
            e.consume();
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new org.edisoncor.gui.panel.Panel();
        Textbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cattipoorden = new javax.swing.JTable();
        salircat = new javax.swing.JButton();
        nuevatipoorden = new javax.swing.JButton();
        panel2 = new org.edisoncor.gui.panel.Panel();
        idpatologia1 = new java.awt.TextField();
        leyenda = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(471, 433));
        setMinimumSize(new java.awt.Dimension(471, 433));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(471, 433));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
        cat.setMaximumSize(new java.awt.Dimension(471, 433));
        cat.setMinimumSize(new java.awt.Dimension(471, 433));

        Textbusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextbusquedaFocusGained(evt);
            }
        });
        Textbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyTyped(evt);
            }
        });

        Cattipoorden.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Cattipoorden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tipo de Orden"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Cattipoorden.setToolTipText("Tipo de Orden");
        Cattipoorden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cattipoorden.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CattipoordenFocusGained(evt);
            }
        });
        Cattipoorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CattipoordenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CattipoordenKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Cattipoorden);

        salircat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
        salircat.setText("Salir");
        salircat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salircat.setMaximumSize(new java.awt.Dimension(112, 30));
        salircat.setMinimumSize(new java.awt.Dimension(112, 30));
        salircat.setPreferredSize(new java.awt.Dimension(112, 30));

        nuevatipoorden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/registrar.png"))); // NOI18N
        nuevatipoorden.setText("Nuevo");
        nuevatipoorden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevatipoorden.setMaximumSize(new java.awt.Dimension(112, 30));
        nuevatipoorden.setMinimumSize(new java.awt.Dimension(112, 30));
        nuevatipoorden.setPreferredSize(new java.awt.Dimension(112, 30));
        nuevatipoorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevatipoordenActionPerformed(evt);
            }
        });

        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-tiposdeordenes.png"))); // NOI18N
        panel2.setMaximumSize(new java.awt.Dimension(471, 75));
        panel2.setPreferredSize(new java.awt.Dimension(471, 75));

        idpatologia1.setVisible(false);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(idpatologia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(idpatologia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout catLayout = new javax.swing.GroupLayout(cat);
        cat.setLayout(catLayout);
        catLayout.setHorizontalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(catLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Textbusqueda)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(catLayout.createSequentialGroup()
                        .addComponent(nuevatipoorden, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(catLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catLayout.setVerticalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catLayout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Textbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevatipoorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        add(cat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TextbusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextbusquedaFocusGained
        String Leyend = "Buscar en el catálogo el registro de tipos de orden…";
        this.getLeyenda().setText(Leyend);
    }//GEN-LAST:event_TextbusquedaFocusGained

    private void TextbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TextbusquedaKeyReleased

    private void TextbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyTyped
            this.validar(evt);
    }//GEN-LAST:event_TextbusquedaKeyTyped

    private void CattipoordenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CattipoordenKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CattipoordenKeyReleased

    private void CattipoordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CattipoordenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CattipoordenKeyTyped

    private void nuevatipoordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevatipoordenActionPerformed
       
    }//GEN-LAST:event_nuevatipoordenActionPerformed

    private void CattipoordenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CattipoordenFocusGained
        String Leyend = "Seleccione el tipo de orden que desee";
        this.getLeyenda().setText(Leyend);
    }//GEN-LAST:event_CattipoordenFocusGained

private void centraVentana() {
//Obtiene el tamaño de la pantalla
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
// Obtiene el tamaño de la ventana de la aplicación
Dimension frameSize = getSize();
// Se asegura que el tamaño de la ventana de la aplicación
// no exceda el tamaño de la pantalla
if (frameSize.height > screenSize.height) {
frameSize.height = screenSize.height;
}
if (frameSize.width > screenSize.width) {
frameSize.width = screenSize.width;
}
// Centra la ventana de la aplicación sobre la pantalla
setLocation((screenSize.width - frameSize.width) / 2,
(screenSize.height - frameSize.height) / 2);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Cattipoorden;
    private javax.swing.JTextField Textbusqueda;
    private org.edisoncor.gui.panel.Panel cat;
    public java.awt.TextField idpatologia1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leyenda;
    public javax.swing.JButton nuevatipoorden;
    private org.edisoncor.gui.panel.Panel panel2;
    private javax.swing.JButton salircat;
    // End of variables declaration//GEN-END:variables
}
