/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorCattipoproducto;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author Jnatn'h
 */
public class CatTipoproducto extends java.awt.Dialog {
    
    private ControladorCattipoproducto controlador;
    
    public void setController(ControladorCattipoproducto controller){
        this.controlador = controller;
        this.asignarlistener();
    }
    public ControladorCattipoproducto getController(){
        return this.controlador;
    }
    private void asignarlistener(){
        Textbusqueda.addKeyListener(getController());
        Cattipoproducto.addMouseListener(getController());
        nuevotipoproducto.addActionListener(getController());
        salircat.addActionListener(getController());
        
    }
    public JTextField getTextbusqueda(){
        return Textbusqueda;
    }
    public void setTextBusqueda(JTextField Textbusqueda){
        this.Textbusqueda = Textbusqueda;
    }
     public JTable getCattipoproducto(){
        return Cattipoproducto;
    }
    public void setCattipoproducto(JTable Cattipoproducto){
        this.Cattipoproducto = Cattipoproducto;
    }
    public JLabel getLeyenda(){
        return leyenda;
    }
    public void setLeyenda(JLabel Leyenda){
        this.leyenda = Leyenda;
    }
    public JButton getNuevotipoproducto(){
        return nuevotipoproducto;
    }
    public void setNuevotipoproducto(JButton nuevotipoproducto){
        this.nuevotipoproducto = nuevotipoproducto;
    }
    public JButton getSalircat(){
        return salircat;
    }
    public void setSalircat(JButton salircat){
        this.salircat = salircat;
    }
    /**
     * Creates new form CatTipoproducto
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
     */
    public CatTipoproducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centraVentana();
        this.setTitle("Tipos de Productos");
        this.setResizable(false);
        setController(new ControladorCattipoproducto(this));
        
    }
    private void centraVentana() {
        //Obtiene el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtiene el tamaño de la ventana de la aplicación
        Dimension frameSize = getSize();
        // Se asegura que el tamaño de la ventana de la aplicación
        // no exceda el tamaño de la pantalla
        if (frameSize.height > screenSize.height) {
        frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
        frameSize.width = screenSize.width;
        }
        // Centra la ventana de la aplicación sobre la pantalla
        setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new org.edisoncor.gui.panel.Panel();
        Textbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cattipoproducto = new javax.swing.JTable();
        salircat = new javax.swing.JButton();
        nuevotipoproducto = new javax.swing.JButton();
        header = new org.edisoncor.gui.panel.Panel();
        leyenda = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(473, 408));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N

        Textbusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextbusquedaFocusGained(evt);
            }
        });
        Textbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyTyped(evt);
            }
        });

        Cattipoproducto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Cattipoproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tipo de Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Cattipoproducto.setToolTipText("Tipo de Producto");
        Cattipoproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cattipoproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CattipoproductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CattipoproductoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Cattipoproducto);

        salircat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
        salircat.setText("Salir");
        salircat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nuevotipoproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/registrar.png"))); // NOI18N
        nuevotipoproducto.setText("Nuevo");
        nuevotipoproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevotipoproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevotipoproductoActionPerformed(evt);
            }
        });

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-tipodeproductos.png"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(473, 75));
        header.setPreferredSize(new java.awt.Dimension(473, 75));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout catLayout = new javax.swing.GroupLayout(cat);
        cat.setLayout(catLayout);
        catLayout.setHorizontalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(catLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Textbusqueda)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(catLayout.createSequentialGroup()
                        .addComponent(nuevotipoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(catLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catLayout.setVerticalGroup(
            catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Textbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevotipoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        add(cat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TextbusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextbusquedaFocusGained
        String Leyend = "Buscar en el catálogo el registro de tipos de productos... ";
        this.getLeyenda().setText(Leyend);
    }//GEN-LAST:event_TextbusquedaFocusGained

    private void TextbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TextbusquedaKeyReleased

    private void TextbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyTyped

    }//GEN-LAST:event_TextbusquedaKeyTyped

    private void CattipoproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CattipoproductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CattipoproductoKeyReleased

    private void CattipoproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CattipoproductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CattipoproductoKeyTyped

    private void nuevotipoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevotipoproductoActionPerformed

    }//GEN-LAST:event_nuevotipoproductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Cattipoproducto;
    private javax.swing.JTextField Textbusqueda;
    private org.edisoncor.gui.panel.Panel cat;
    private org.edisoncor.gui.panel.Panel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leyenda;
    private javax.swing.JButton nuevotipoproducto;
    private javax.swing.JButton salircat;
    // End of variables declaration//GEN-END:variables
}
