/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorOpcAdministrativas;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author Jnatn'h
 */
public class OpcionesAdministrativas extends java.awt.Dialog {
  
  private ControladorOpcAdministrativas controller;

  public ControladorOpcAdministrativas getController() {
    return controller;
  }

  public void setController(ControladorOpcAdministrativas controller) {
    this.controller = controller;
    this.asignaroyentes();
  }
  
  private void asignaroyentes(){
    getGrabar().addActionListener(getController());
    getModificar().addActionListener(getController());
    getEliminar().addActionListener(getController());
    getSalir().addActionListener(getController());
    
  }
  public JButton getEliminar() {
    return Eliminar;
  }

  public void setEliminar(JButton Eliminar) {
    this.Eliminar = Eliminar;
  }

  public JButton getGrabar() {
    return Grabar;
  }

  public void setGrabar(JButton Grabar) {
    this.Grabar = Grabar;
  }

  public JLabel getLeyenda() {
    return Leyenda;
  }

  public void setLeyenda(JLabel Leyenda) {
    this.Leyenda = Leyenda;
  }

  public JButton getModificar() {
    return Modificar;
  }

  public void setModificar(JButton Modificar) {
    this.Modificar = Modificar;
  }

  public JButton getSalir() {
    return Salir;
  }

  public void setSalir(JButton Salir) {
    this.Salir = Salir;
  }

  public JTextField getOpcion() {
    return opcion;
  }

  public void setOpcion(JTextField opcion) {
    this.opcion = opcion;
  }
  /**
   * Creates new form OpcionesAdministrativas
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
   */
  public OpcionesAdministrativas(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setResizable(false);
    setTitle("Opciones Administrativas");
    this.setLocationRelativeTo(null);
  }
  private void validarcampo(KeyEvent e){
     char b = e.getKeyChar();
         if(!Character.isLetter(b) &&  b != KeyEvent.VK_SPACE ){
            e.consume();
    }     
         if( this.getOpcion().getText().length() >= 50){
        e.consume();
    }
}
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new org.edisoncor.gui.panel.Panel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        opcion = new javax.swing.JTextField();
        Grabar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Leyenda = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(700, 245));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
        panel.setMaximumSize(new java.awt.Dimension(700, 245));
        panel.setMinimumSize(new java.awt.Dimension(700, 245));
        panel.setPreferredSize(new java.awt.Dimension(700, 245));

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-opcionadministrativa.png"))); // NOI18N
        panel1.setMaximumSize(new java.awt.Dimension(700, 75));
        panel1.setMinimumSize(new java.awt.Dimension(700, 75));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        opcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                opcionFocusGained(evt);
            }
        });
        opcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                opcionKeyTyped(evt);
            }
        });

        Grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/Floppy-Small-icon.png"))); // NOI18N
        Grabar.setText("Registrar");
        Grabar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Grabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Grabar.setMaximumSize(new java.awt.Dimension(112, 30));
        Grabar.setMinimumSize(new java.awt.Dimension(112, 30));
        Grabar.setPreferredSize(new java.awt.Dimension(112, 30));

        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/modificar.png"))); // NOI18N
        Modificar.setText("Modificar");
        Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar.setMaximumSize(new java.awt.Dimension(112, 30));
        Modificar.setMinimumSize(new java.awt.Dimension(112, 30));
        Modificar.setPreferredSize(new java.awt.Dimension(112, 30));

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/eliminar.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.setMaximumSize(new java.awt.Dimension(112, 30));
        Eliminar.setMinimumSize(new java.awt.Dimension(112, 30));
        Eliminar.setPreferredSize(new java.awt.Dimension(112, 30));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setMaximumSize(new java.awt.Dimension(112, 30));
        Salir.setMinimumSize(new java.awt.Dimension(112, 30));
        Salir.setPreferredSize(new java.awt.Dimension(112, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Leyenda.setForeground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(Grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opcion, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Grabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        add(panel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * Closes the dialog
   */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
      setVisible(false);
 
    }//GEN-LAST:event_closeDialog

  private void opcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opcionFocusGained
    String leyen = "Ingrese o modifique la opción administrativa";
    this.getLeyenda().setText(leyen);
    this.getLeyenda().setForeground(Color.white);
  }//GEN-LAST:event_opcionFocusGained

  private void opcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opcionKeyPressed
    // TODO add your handling code here:
    char a = evt.getKeyChar();
    if (KeyEvent.VK_PASTE == a){
      evt.consume();
  }//GEN-LAST:event_opcionKeyPressed
 }
  private void opcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opcionKeyTyped
    this.validarcampo(evt);
  }//GEN-LAST:event_opcionKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Grabar;
    public javax.swing.JLabel Leyenda;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField opcion;
    private org.edisoncor.gui.panel.Panel panel;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
