/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Jnatn'h
 */
public class Ordenes extends javax.swing.JDialog {

  public JLabel getLeyenda() {
    return Leyenda;
  }

  public void setLeyenda(JLabel Leyenda) {
    this.Leyenda = Leyenda;
  }

  public JButton getSalir() {
    return Salir;
  }

  public void setSalir(JButton Salir) {
    this.Salir = Salir;
  }

  public JButton getAnadir() {
    return anadir;
  }

  public void setAnadir(JButton anadir) {
    this.anadir = anadir;
  }

  public JButton getAsignarpatologia() {
    return asignarpatologia;
  }

  public void setAsignarpatologia(JButton asignarpatologia) {
    this.asignarpatologia = asignarpatologia;
  }

  /**
   * Creates new form Ordenes
   */
  public Ordenes(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel5 = new org.edisoncor.gui.panel.Panel();
    header = new org.edisoncor.gui.panel.Panel();
    center = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    temperatura1 = new javax.swing.JLabel();
    movimiento = new javax.swing.JTabbedPane();
    consulta = new javax.swing.JPanel();
    jLabel17 = new javax.swing.JLabel();
    jScrollPane5 = new javax.swing.JScrollPane();
    sintoma = new javax.swing.JTextArea();
    jLabel18 = new javax.swing.JLabel();
    jScrollPane6 = new javax.swing.JScrollPane();
    diagnostico = new javax.swing.JTextArea();
    jLabel19 = new javax.swing.JLabel();
    asignarpatologia = new javax.swing.JButton();
    patologias = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    Patologias = new javax.swing.JList<>();
    jScrollPane7 = new javax.swing.JScrollPane();
    seleccionada = new javax.swing.JList<>();
    anadir = new javax.swing.JButton();
    quitar = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    triaje = new javax.swing.JPanel();
    peso = new javax.swing.JLabel();
    talla = new javax.swing.JLabel();
    temperatura = new javax.swing.JLabel();
    tension = new javax.swing.JLabel();
    glicemia = new javax.swing.JLabel();
    observaciontriaje = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    ordenes = new javax.swing.JList<>();
    temperatura2 = new javax.swing.JLabel();
    dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
    footer = new javax.swing.JPanel();
    dfooter = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    historiamedica = new javax.swing.JButton();
    Procesar = new javax.swing.JButton();
    Salir = new javax.swing.JButton();
    Leyenda = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    panel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
    panel5.setMaximumSize(new java.awt.Dimension(771, 457));
    panel5.setPreferredSize(new java.awt.Dimension(771, 452));
    panel5.setLayout(new java.awt.BorderLayout());

    header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-consulta.png"))); // NOI18N
    header.setMaximumSize(new java.awt.Dimension(771, 75));
    header.setMinimumSize(new java.awt.Dimension(771, 75));

    javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
    header.setLayout(headerLayout);
    headerLayout.setHorizontalGroup(
      headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 771, Short.MAX_VALUE)
    );
    headerLayout.setVerticalGroup(
      headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 75, Short.MAX_VALUE)
    );

    panel5.add(header, java.awt.BorderLayout.NORTH);

    center.setOpaque(false);
    center.setLayout(new javax.swing.BoxLayout(center, javax.swing.BoxLayout.LINE_AXIS));

    jPanel2.setOpaque(false);

    temperatura1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    temperatura1.setForeground(new java.awt.Color(255, 255, 255));
    temperatura1.setText("Tipo de órdenes");
    temperatura1.setToolTipText("");

    movimiento.setMaximumSize(new java.awt.Dimension(400, 600));

    jLabel17.setForeground(new java.awt.Color(0, 0, 0));
    jLabel17.setText("Síntoma:");

    sintoma.setColumns(20);
    sintoma.setLineWrap(true);
    sintoma.setRows(2);
    sintoma.setEnabled(false);
    sintoma.setMaximumSize(new java.awt.Dimension(220, 80));
    sintoma.setName(""); // NOI18N
    sintoma.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        sintomaFocusGained(evt);
      }
    });
    jScrollPane5.setViewportView(sintoma);

    jLabel18.setForeground(new java.awt.Color(0, 0, 0));
    jLabel18.setText("Diagnóstico:");

    diagnostico.setColumns(20);
    diagnostico.setLineWrap(true);
    diagnostico.setRows(5);
    diagnostico.setEnabled(false);
    diagnostico.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        diagnosticoFocusGained(evt);
      }
    });
    jScrollPane6.setViewportView(diagnostico);

    jLabel19.setForeground(new java.awt.Color(0, 0, 0));
    jLabel19.setText("Patología:");

    asignarpatologia.setText("Asignar Patologías");
    asignarpatologia.setToolTipText("Asignación de patologias");
    asignarpatologia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    asignarpatologia.setEnabled(false);

    javax.swing.GroupLayout consultaLayout = new javax.swing.GroupLayout(consulta);
    consulta.setLayout(consultaLayout);
    consultaLayout.setHorizontalGroup(
      consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(consultaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel17)
          .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(asignarpatologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel18)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    consultaLayout.setVerticalGroup(
      consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(consultaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel17)
          .addComponent(jLabel18)
          .addComponent(jScrollPane6)
          .addComponent(jScrollPane5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(asignarpatologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    movimiento.addTab("Consulta", consulta);

    patologias.setEnabled(false);

    Patologias.setToolTipText("Seleccione una o mas patologías");
    Patologias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Patologias.setEnabled(false);
    jScrollPane2.setViewportView(Patologias);

    seleccionada.setForeground(new java.awt.Color(0, 0, 0));
    seleccionada.setToolTipText("");
    seleccionada.setEnabled(false);
    jScrollPane7.setViewportView(seleccionada);

    anadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/der.png"))); // NOI18N
    anadir.setToolTipText("");
    anadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    anadir.setEnabled(false);
    anadir.setIconTextGap(10);

    quitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/izq.png"))); // NOI18N
    quitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    quitar.setEnabled(false);

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setText("Patologías:");

    jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    jLabel6.setText("Patologías Asignadas");
    jLabel6.setToolTipText("");

    javax.swing.GroupLayout patologiasLayout = new javax.swing.GroupLayout(patologias);
    patologias.setLayout(patologiasLayout);
    patologiasLayout.setHorizontalGroup(
      patologiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(patologiasLayout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(patologiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(patologiasLayout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(patologiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(anadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(quitar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31)
        .addGroup(patologiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane7))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    patologiasLayout.setVerticalGroup(
      patologiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(patologiasLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(patologiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(patologiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
          .addGroup(patologiasLayout.createSequentialGroup()
            .addComponent(anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    movimiento.addTab("Patologías", patologias);

    triaje.setEnabled(false);

    peso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    peso.setForeground(new java.awt.Color(0, 0, 0));
    peso.setText("Peso:");
    peso.setToolTipText("");

    talla.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    talla.setForeground(new java.awt.Color(0, 0, 0));
    talla.setText("Talla:");
    talla.setToolTipText("");

    temperatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    temperatura.setForeground(new java.awt.Color(0, 0, 0));
    temperatura.setText("Temperatura:");
    temperatura.setToolTipText("");

    tension.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    tension.setForeground(new java.awt.Color(0, 0, 0));
    tension.setText("Tensión:");
    tension.setToolTipText("");

    glicemia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    glicemia.setForeground(new java.awt.Color(0, 0, 0));
    glicemia.setText("Glicemia:");
    glicemia.setToolTipText("");

    observaciontriaje.setText("Observación");
    observaciontriaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    observaciontriaje.setEnabled(false);

    javax.swing.GroupLayout triajeLayout = new javax.swing.GroupLayout(triaje);
    triaje.setLayout(triajeLayout);
    triajeLayout.setHorizontalGroup(
      triajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(triajeLayout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(triajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(observaciontriaje, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(triajeLayout.createSequentialGroup()
            .addGroup(triajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(tension, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
              .addComponent(peso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(triajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(talla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(glicemia, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    triajeLayout.setVerticalGroup(
      triajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(triajeLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(triajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(peso)
          .addComponent(talla)
          .addComponent(temperatura))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(triajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(tension)
          .addComponent(glicemia))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(observaciontriaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    movimiento.addTab("Triage", triaje);

    ordenes.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "sdfsadfasdf", "sadf", "asdf", "asd", "fasd", "fasd", "fas", "dfas", "dfasdf" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(ordenes);

    temperatura2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    temperatura2.setForeground(new java.awt.Color(255, 255, 255));
    temperatura2.setText("Vencimiento");
    temperatura2.setToolTipText("");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap(55, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(52, 52, 52))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(temperatura2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(242, 242, 242))))
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
          .addContainerGap(57, Short.MAX_VALUE)
          .addComponent(temperatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(573, Short.MAX_VALUE)))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(temperatura2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(33, 33, 33))
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(temperatura1)
          .addContainerGap(272, Short.MAX_VALUE)))
    );

    center.add(jPanel2);

    panel5.add(center, java.awt.BorderLayout.CENTER);

    footer.setOpaque(false);

    dfooter.setOpaque(false);
    dfooter.setLayout(new java.awt.GridLayout(2, 1, 50, 0));

    jPanel1.setOpaque(false);
    jPanel1.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

    historiamedica.setText("Historia Médica");
    historiamedica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    historiamedica.setEnabled(false);
    jPanel1.add(historiamedica);

    Procesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/Floppy-Small-icon.png"))); // NOI18N
    Procesar.setText("Procesar");
    Procesar.setToolTipText("");
    Procesar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Procesar.setEnabled(false);
    Procesar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ProcesarActionPerformed(evt);
      }
    });
    jPanel1.add(Procesar);

    Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
    Salir.setText("Salir");
    Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel1.add(Salir);

    dfooter.add(jPanel1);

    Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    Leyenda.setForeground(new java.awt.Color(255, 255, 255));
    dfooter.add(Leyenda);

    javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
    footer.setLayout(footerLayout);
    footerLayout.setHorizontalGroup(
      footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(dfooter, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
    );
    footerLayout.setVerticalGroup(
      footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
        .addGap(0, 19, Short.MAX_VALUE)
        .addComponent(dfooter, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    panel5.add(footer, java.awt.BorderLayout.SOUTH);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 771, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 457, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ProcesarActionPerformed

  private void sintomaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sintomaFocusGained
    String leyenda = "Describir el síntoma presentado por el paciente...";
    getLeyenda().setText(leyenda);
  }//GEN-LAST:event_sintomaFocusGained

  private void diagnosticoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diagnosticoFocusGained
    String leyenda = "Especifíque el diagnóstico encontrado...";
    getLeyenda().setText(leyenda);
  }//GEN-LAST:event_diagnosticoFocusGained

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Ordenes dialog = new Ordenes(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JLabel Leyenda;
  private javax.swing.JList<String> Patologias;
  private javax.swing.JButton Procesar;
  private javax.swing.JButton Salir;
  private javax.swing.JButton anadir;
  private javax.swing.JButton asignarpatologia;
  private javax.swing.JPanel center;
  private javax.swing.JPanel consulta;
  private datechooser.beans.DateChooserCombo dateChooserCombo1;
  private javax.swing.JPanel dfooter;
  private javax.swing.JTextArea diagnostico;
  private javax.swing.JPanel footer;
  private javax.swing.JLabel glicemia;
  private org.edisoncor.gui.panel.Panel header;
  private javax.swing.JButton historiamedica;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JScrollPane jScrollPane7;
  private javax.swing.JTabbedPane movimiento;
  private javax.swing.JButton observaciontriaje;
  private javax.swing.JList<String> ordenes;
  private org.edisoncor.gui.panel.Panel panel5;
  private javax.swing.JPanel patologias;
  private javax.swing.JLabel peso;
  private javax.swing.JButton quitar;
  private javax.swing.JList<String> seleccionada;
  private javax.swing.JTextArea sintoma;
  private javax.swing.JLabel talla;
  private javax.swing.JLabel temperatura;
  private javax.swing.JLabel temperatura1;
  private javax.swing.JLabel temperatura2;
  private javax.swing.JLabel tension;
  private javax.swing.JPanel triaje;
  // End of variables declaration//GEN-END:variables
}
