/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import Controlador.ControladorPactivo;
import java.awt.Dimension;
import java.awt.Event;
import java.awt.Toolkit;
import javax.swing.InputMap;
import javax.swing.KeyStroke;

/**
 *
 * @author Jnatn'h
 */
public class Pactivo extends java.awt.Dialog {
    ControladorPactivo controlador;
    int idpactivo;
     public void Idpactivo(int Idpactivo)
    {
        this.idpactivo = Idpactivo;
        this.setIdpactivo(idpactivo);
    }
      public int getIdpactivo()
    {
        return idpactivo;
    }
    public void setIdpactivo(int idpactivo)
    {
        this.idpactivo = idpactivo;
         
    }
    public JLabel getLeyenda()
    {
        return Leyenda;
    }
    public void setLeyenda(JLabel Leyenda)
    {
        this.Leyenda = Leyenda;
    }
    
    public JTextField getTextpactivo ()
    {
        return Textpactivo;
    }
    public void setTextpactivo(JTextField Textpactivo)
    {
        this.Textpactivo = Textpactivo;
    }
    
    public JButton getRegistrar()
    {
        return Registrar;
    }
    public void setRegistrar(JButton Registrar)
    {
        this.Registrar = Registrar;
    }
     public JButton getModificar()
    {
        return Modificar;
    }
    public void setModificar(JButton Modificar)
    {
        this.Modificar = Modificar;
    }
     public JButton getEliminar()
    {
        return Eliminar;
    }
    public void setEliminar(JButton Eliminar)
    {
        this.Eliminar = Eliminar;
    }
     public JButton getSalir()
    {
        return Salir;
    }
    public void setSalir(JButton Salir)
    {
        this.Salir = Salir;
    }
    /**
     * Creates new form Pactivo
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
     */
    public Pactivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Principio activo");
        this.setResizable(false);
        centraVentana();
    
        this.desabilitaroptionpegar(this.getTextpactivo());
    }
 public void desabilitaroptionpegar(JTextField text){
        InputMap map = text.getInputMap();
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_INSERT, Event.SHIFT_MASK), "null");
}
        
  private void centraVentana() 
{
    //Obtiene el tamaño de la pantalla
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    // Obtiene el tamaño de la ventana de la aplicación
    Dimension frameSize = getSize();
    // Se asegura que el tamaño de la ventana de la aplicación
    // no exceda el tamaño de la pantalla
    if (frameSize.height > screenSize.height) {
    frameSize.height = screenSize.height;
    }
    if (frameSize.width > screenSize.width) {
    frameSize.width = screenSize.width;
    }
    // Centra la ventana de la aplicación sobre la pantalla
    setLocation((screenSize.width - frameSize.width) / 2,
    (screenSize.height - frameSize.height) / 2);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel1 = new org.edisoncor.gui.panel.Panel();
    panel2 = new org.edisoncor.gui.panel.Panel();
    idpatologia1 = new java.awt.TextField();
    Textpactivo = new javax.swing.JTextField();
    Registrar = new javax.swing.JButton();
    Modificar = new javax.swing.JButton();
    Eliminar = new javax.swing.JButton();
    Salir = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    Leyenda = new javax.swing.JLabel();

    setMaximumSize(new java.awt.Dimension(636, 250));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N

    panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-principioactivo.png"))); // NOI18N
    panel2.setMaximumSize(new java.awt.Dimension(636, 75));
    panel2.setPreferredSize(new java.awt.Dimension(636, 75));

    idpatologia1.setVisible(false);

    javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
    panel2.setLayout(panel2Layout);
    panel2Layout.setHorizontalGroup(
      panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panel2Layout.createSequentialGroup()
        .addGap(231, 231, 231)
        .addComponent(idpatologia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panel2Layout.setVerticalGroup(
      panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panel2Layout.createSequentialGroup()
        .addContainerGap(75, Short.MAX_VALUE)
        .addComponent(idpatologia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    Textpactivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    Textpactivo.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        TextpactivoFocusGained(evt);
      }
    });
    Textpactivo.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        TextpactivoKeyTyped(evt);
      }
    });

    Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/Floppy-Small-icon.png"))); // NOI18N
    Registrar.setText("Registrar");
    Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/modificar.png"))); // NOI18N
    Modificar.setText("Modificar");
    Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/eliminar.png"))); // NOI18N
    Eliminar.setText("Eliminar");
    Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
    Salir.setText("Salir");
    Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Nombre:");

    Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    Leyenda.setForeground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
    panel1.setLayout(panel1Layout);
    panel1Layout.setHorizontalGroup(
      panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(panel1Layout.createSequentialGroup()
        .addGap(39, 39, 39)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(panel1Layout.createSequentialGroup()
            .addComponent(Registrar)
            .addGap(18, 18, 18)
            .addComponent(Modificar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Eliminar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Salir))
          .addComponent(Textpactivo))
        .addContainerGap(67, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panel1Layout.setVerticalGroup(
      panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Textpactivo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        .addGap(26, 26, 26)
        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        .addComponent(Leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    controlador = new Controlador.ControladorPactivo(this);
    Registrar.addActionListener(controlador);
    controlador = new Controlador.ControladorPactivo(this);
    Modificar.addActionListener(controlador);
    controlador = new Controlador.ControladorPactivo(this);
    Eliminar.addActionListener(controlador);
    controlador = new Controlador.ControladorPactivo(this);
    Salir.addActionListener(controlador);

    add(panel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TextpactivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextpactivoFocusGained
        String leyen = "Ingrese o modifique el Principio activo";
        this.getLeyenda().setText(leyen);
        this.getLeyenda().setForeground(Color.white);
    }//GEN-LAST:event_TextpactivoFocusGained

    private void TextpactivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextpactivoKeyTyped
        this.validarcampo(evt);
    }//GEN-LAST:event_TextpactivoKeyTyped
  private void validarcampo(KeyEvent e)
    {
        String caracter  = this.getTextpactivo().toString();
     char b = e.getKeyChar();
         if(!Character.isLetter(b) &&  b != KeyEvent.VK_SPACE){
            e.consume();
    }     
         if( this.getTextpactivo().getText().length() >= 30)
    {
        e.consume();
    }
//        if(!caracter.isEmpty())
//        caracter=caracter.substring(0,caracter.length()-1);
//        caracter+=String.valueOf(b).toUpperCase();
//        this.getTextpotencia().setText(caracter);
}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Eliminar;
  public javax.swing.JLabel Leyenda;
  private javax.swing.JButton Modificar;
  private javax.swing.JButton Registrar;
  private javax.swing.JButton Salir;
  private javax.swing.JTextField Textpactivo;
  public java.awt.TextField idpatologia1;
  private javax.swing.JLabel jLabel1;
  private org.edisoncor.gui.panel.Panel panel1;
  private org.edisoncor.gui.panel.Panel panel2;
  // End of variables declaration//GEN-END:variables
}
