/*
 * The MIT License
 *
 * Copyright 2017 Jnatn'h.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package Vista;

import Controlador.ControladorMorbilidad;
import datechooser.beans.DateChooserPanel;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Jnatn'h
 */
public class rangocalendar extends java.awt.Dialog {

    private ControladorMorbilidad contr;
    public void setController(ControladorMorbilidad cont){
        this.contr = cont;
        this.asignarListener();
    }
    public ControladorMorbilidad getController(){
        return this.contr;
    }
    private void asignarListener(){
        this.Asignar.addActionListener(contr);
        this.salircalendario.addActionListener(contr);
        this.siguiente.addActionListener(contr);
    }
    public JButton getAsignar() {
        return Asignar;
    }

    public JButton getSiguiente() {
        return siguiente;
    }

    public JLabel getLeyendacalendario() {
        return leyendacalendario;
    }

    public void setLeyendacalendario(JLabel leyendacalendario) {
        this.leyendacalendario = leyendacalendario;
    }

    public void setSiguiente(JButton siguiente) {
        this.siguiente = siguiente;
    }

    public void setAsignar(JButton Asignar) {
        this.Asignar = Asignar;
    }

    public DateChooserPanel getFechaFinal() {
        return FechaFinal;
    }

    public void setFechaFinal(DateChooserPanel FechaFinal) {
        this.FechaFinal = FechaFinal;
    }

    public JTabbedPane getAsignacionfecha() {
        return asignacionfecha;
    }

    public void setAsignacionfecha(JTabbedPane asignacionfecha) {
        this.asignacionfecha = asignacionfecha;
    }

    public DateChooserPanel getFechainicial() {
        return fechainicial;
    }

    public void setFechainicial(DateChooserPanel fechainicial) {
        this.fechainicial = fechainicial;
    }

    public JButton getSalircalendario() {
        return salircalendario;
    }

    public void setSalircalendario(JButton salircalendario) {
        this.salircalendario = salircalendario;
    }

    /**
     * Creates new form rangocalendar
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
     */
    public rangocalendar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setModal(modal);
        setResizable(false);
        Date fch = new Date();
        GregorianCalendar fchh = new GregorianCalendar();
        TimeZone tz = fchh.getTimeZone();
        fechainicial.setMaxDate(new java.util.GregorianCalendar(tz));
        FechaFinal.setMaxDate(new java.util.GregorianCalendar(tz));
        setTitle("Asignar Rango de fechas");
        String Leyenda = "Asigne los rangos comprendido entre la fecha inicial y final";
        this.leyendacalendario.setText(Leyenda);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat1 = new org.edisoncor.gui.panel.Panel();
        salircalendario = new javax.swing.JButton();
        Asignar = new javax.swing.JButton();
        leyendacalendario = new javax.swing.JLabel();
        asignacionfecha = new javax.swing.JTabbedPane();
        fechainicial = new datechooser.beans.DateChooserPanel();
        FechaFinal = new datechooser.beans.DateChooserPanel();
        siguiente = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
        cat1.setMaximumSize(new java.awt.Dimension(555, 460));
        cat1.setName("Potencia"); // NOI18N
        cat1.setPreferredSize(new java.awt.Dimension(555, 460));

        salircalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
        salircalendario.setText("Salir");
        salircalendario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salircalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salircalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salircalendarioActionPerformed(evt);
            }
        });

        Asignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/reportes.png"))); // NOI18N
        Asignar.setText("Asignar");
        Asignar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Asignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Asignar.setEnabled(false);
        Asignar.setIconTextGap(10);

        leyendacalendario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        leyendacalendario.setForeground(new java.awt.Color(255, 255, 255));

        fechainicial.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);
        asignacionfecha.addTab("Fecha Inicial", fechainicial);

        FechaFinal.setEnabled(false);
        FechaFinal.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_PERIOD);
        asignacionfecha.addTab("Fecha Final", FechaFinal);

        asignacionfecha.setSelectedComponent(fechainicial);

        siguiente.setText("Fecha Final");
        siguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout cat1Layout = new javax.swing.GroupLayout(cat1);
        cat1.setLayout(cat1Layout);
        cat1Layout.setHorizontalGroup(
            cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignacionfecha)
            .addGroup(cat1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(salircalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cat1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(leyendacalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        cat1Layout.setVerticalGroup(
            cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat1Layout.createSequentialGroup()
                .addComponent(asignacionfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salircalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cat1Layout.createSequentialGroup()
                    .addContainerGap(423, Short.MAX_VALUE)
                    .addComponent(leyendacalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        add(cat1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void salircalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salircalendarioActionPerformed
        this.dispose();
    }//GEN-LAST:event_salircalendarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Asignar;
    private datechooser.beans.DateChooserPanel FechaFinal;
    private javax.swing.JTabbedPane asignacionfecha;
    private org.edisoncor.gui.panel.Panel cat1;
    private datechooser.beans.DateChooserPanel fechainicial;
    private javax.swing.JLabel leyendacalendario;
    private javax.swing.JButton salircalendario;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
