/*
 * The MIT License
 *
 * Copyright 2017 Jnatn'h.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package Vista;

import Controlador.ControladorConsulta;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author Jnatn'h
 */
public class Recipe extends java.awt.Dialog {

    private ControladorConsulta controller;
    public void setController(ControladorConsulta cont){
        this.controller = cont;
        this.asignarlistener();
    }
    public ControladorConsulta getController(){
        return this.controller;
    }
    private void asignarlistener(){
        this.getImprimirrecipe().addActionListener(controller);      
    }
    public JLabel getLeyenda() {
        return Leyenda;
    }

    public void setLeyenda(JLabel Leyenda) {
        this.Leyenda = Leyenda;
    }

    public JTextArea getIndicacion() {
        return indicacion;
    }

    public void setIdicacion(JTextArea idicacion) {
        this.indicacion = idicacion;
    }

    public JLabel getNrorecipe() {
        return nrorecipe;
    }

    public void setNrorecipe(JLabel nrorecipe) {
        this.nrorecipe = nrorecipe;
    }

    public JButton getImprimirrecipe() {
        return imprimirrecipe;
    }

    public void setImprimirrecipe(JButton registrar) {
        this.imprimirrecipe = registrar;
    }

    public JButton getSalircat() {
        return salircat;
    }

    public void setSalircat(JButton salircat) {
        this.salircat = salircat;
    }

    
    /**
     * Creates new form Recipe
     * @param parent, una contenedor de primer nivel como lo es Frame. 
     * @param modal, si queremos que sea modal o no ... 
     */
    public Recipe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setModal(modal);
        setResizable(false);
        setTitle("Recipe");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat1 = new org.edisoncor.gui.panel.Panel();
        salircat = new javax.swing.JButton();
        panel2 = new org.edisoncor.gui.panel.Panel();
        Leyenda = new javax.swing.JLabel();
        imprimirrecipe = new javax.swing.JButton();
        nrorecipe = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        indicacion = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
        cat1.setMaximumSize(new java.awt.Dimension(410, 399));
        cat1.setName("Potencia"); // NOI18N
        cat1.setPreferredSize(new java.awt.Dimension(410, 399));

        salircat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
        salircat.setText("Salir");
        salircat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salircat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salircatActionPerformed(evt);
            }
        });

        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-examen.png"))); // NOI18N
        panel2.setMaximumSize(new java.awt.Dimension(410, 75));
        panel2.setMinimumSize(new java.awt.Dimension(410, 75));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Leyenda.setForeground(new java.awt.Color(255, 255, 255));

        imprimirrecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/imprimir.png"))); // NOI18N
        imprimirrecipe.setText("Imprimir");
        imprimirrecipe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nrorecipe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nrorecipe.setForeground(new java.awt.Color(255, 255, 255));
        nrorecipe.setText("Nro de Recipe:");

        indicacion.setColumns(20);
        indicacion.setForeground(new java.awt.Color(0, 0, 0));
        indicacion.setLineWrap(true);
        indicacion.setRows(5);
        indicacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indicación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        indicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                indicacionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(indicacion);

        javax.swing.GroupLayout cat1Layout = new javax.swing.GroupLayout(cat1);
        cat1.setLayout(cat1Layout);
        cat1Layout.setHorizontalGroup(
            cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cat1Layout.createSequentialGroup()
                .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cat1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cat1Layout.createSequentialGroup()
                        .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cat1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nrorecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cat1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cat1Layout.createSequentialGroup()
                                        .addComponent(imprimirrecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(116, 116, 116)
                                        .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        cat1Layout.setVerticalGroup(
            cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nrorecipe)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imprimirrecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salircat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(cat1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void indicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indicacionKeyTyped
      // TODO add your handling code here:
        this.validarcampo(evt);
        if(this.getIndicacion().getText().length() >= 200)
        {
          evt.consume();
        }
    }//GEN-LAST:event_indicacionKeyTyped

    private void salircatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salircatActionPerformed
      this.dispose();
    }//GEN-LAST:event_salircatActionPerformed
    private void validarcampo(KeyEvent e){
     char b = e.getKeyChar();
         if(!Character.isLetter(b)  &&  b != KeyEvent.VK_SPACE){
            e.consume();
         }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Leyenda;
    private org.edisoncor.gui.panel.Panel cat1;
    private javax.swing.JButton imprimirrecipe;
    private javax.swing.JTextArea indicacion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nrorecipe;
    private org.edisoncor.gui.panel.Panel panel2;
    private javax.swing.JButton salircat;
    // End of variables declaration//GEN-END:variables
}
