/*
 * The MIT License
 *
 * Copyright 2017 Jnatn'h.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package Vista;

import Controlador.ControladorConsulta;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;


/**
 *
 * @author Jnatn'h
 */
public class Reposo extends java.awt.Dialog {
    ControladorConsulta controll;
    public void setController(ControladorConsulta cont){
     this.controll = cont;
     this.asignarListener();
    }
    public ControladorConsulta getController(){
        return this.controll;
    }
    private void asignarListener(){
        this.getImprimirreposo().addActionListener(controll);    
    }
    public JLabel getLeyenda() {
        return Leyenda;
    }

    public void setLeyenda(JLabel Leyenda) {
        this.Leyenda = Leyenda;
    }

    public JTextArea getDetalle() {
        return detalle;
    }

    public void setDetalle(JTextArea detalle) {
        this.detalle = detalle;
    }

    public JButton getImprimirreposo() {
        return imprimirreposo;
    }

    public void setImprimirreposo(JButton imprimir) {
        this.imprimirreposo = imprimir;
    }

    public JTextArea getMotivo() {
        return motivo;
    }

    public void setMotivo(JTextArea motivo) {
        this.motivo = motivo;
    }

    public JSpinner getNrodias() {
        return nrodias;
    }

    public void setNrodias(JSpinner nrodias) {
        this.nrodias = nrodias;
    }

    public JLabel getNroreposo() {
        return nroreposo;
    }

    public void setNroreposo(JLabel nroreposo) {
        this.nroreposo = nroreposo;
    }

    public JButton getSalircat() {
        return salirreposo;
    }

    public void setSalircat(JButton salircat) {
        this.salirreposo = salircat;
    }

    public JLabel getPaciente() {
        return paciente;
    }

    public void setPaciente(JLabel paciente) {
        this.paciente = paciente;
    }

    

    
    /** Creates new form Reposo
     * @param parent  una contenedor de primer nivel como lo es Frame. 
     * @param modal si queremos que sea modal o no ... 
     */
    public Reposo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(modal);
        setResizable(false);
        setTitle("Reposo");
        setLocationRelativeTo(null);
//        SpinnerNumberModel model = new SpinnerNumberModel(10, 0, 7, 1);       
//        nrodias.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cat1 = new org.edisoncor.gui.panel.Panel();
    salirreposo = new javax.swing.JButton();
    panel2 = new org.edisoncor.gui.panel.Panel();
    Leyenda = new javax.swing.JLabel();
    imprimirreposo = new javax.swing.JButton();
    nroreposo = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    motivo = new javax.swing.JTextArea();
    sdfsdf = new javax.swing.JLabel();
    nrodias = new javax.swing.JSpinner();
    jScrollPane3 = new javax.swing.JScrollPane();
    detalle = new javax.swing.JTextArea();
    paciente = new javax.swing.JLabel();

    setMaximumSize(new java.awt.Dimension(806, 399));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    cat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
    cat1.setMaximumSize(new java.awt.Dimension(806, 399));
    cat1.setName("Potencia"); // NOI18N
    cat1.setPreferredSize(new java.awt.Dimension(806, 399));

    salirreposo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
    salirreposo.setText("Salir");
    salirreposo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    salirreposo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        salirreposoActionPerformed(evt);
      }
    });

    panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-usuario.png"))); // NOI18N
    panel2.setMaximumSize(new java.awt.Dimension(410, 75));
    panel2.setMinimumSize(new java.awt.Dimension(410, 75));

    javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
    panel2.setLayout(panel2Layout);
    panel2Layout.setHorizontalGroup(
      panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panel2Layout.setVerticalGroup(
      panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 75, Short.MAX_VALUE)
    );

    Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    Leyenda.setForeground(new java.awt.Color(255, 255, 255));

    imprimirreposo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/imprimir.png"))); // NOI18N
    imprimirreposo.setText("Imprimir");
    imprimirreposo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    nroreposo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    nroreposo.setForeground(new java.awt.Color(255, 255, 255));
    nroreposo.setText("Nro de Reposo:");

    motivo.setColumns(20);
    motivo.setForeground(new java.awt.Color(0, 0, 0));
    motivo.setLineWrap(true);
    motivo.setRows(5);
    motivo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
    motivo.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        motivoKeyTyped(evt);
      }
    });
    jScrollPane2.setViewportView(motivo);

    sdfsdf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    sdfsdf.setForeground(new java.awt.Color(255, 255, 255));
    sdfsdf.setText("Días de reposo:");

    nrodias.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        nrodiasStateChanged(evt);
      }
    });

    detalle.setColumns(20);
    detalle.setForeground(new java.awt.Color(0, 0, 0));
    detalle.setLineWrap(true);
    detalle.setRows(5);
    detalle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
    detalle.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        detalleKeyTyped(evt);
      }
    });
    jScrollPane3.setViewportView(detalle);

    paciente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    paciente.setForeground(new java.awt.Color(255, 255, 255));
    paciente.setText("Paciente:");

    javax.swing.GroupLayout cat1Layout = new javax.swing.GroupLayout(cat1);
    cat1.setLayout(cat1Layout);
    cat1Layout.setHorizontalGroup(
      cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(cat1Layout.createSequentialGroup()
        .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cat1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(Leyenda, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
          .addGroup(cat1Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(cat1Layout.createSequentialGroup()
                .addComponent(nroreposo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sdfsdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrodias, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(cat1Layout.createSequentialGroup()
                  .addComponent(imprimirreposo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(salirreposo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cat1Layout.createSequentialGroup()
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        .addContainerGap())
    );
    cat1Layout.setVerticalGroup(
      cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(cat1Layout.createSequentialGroup()
        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(nrodias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(sdfsdf)
          .addComponent(nroreposo)
          .addComponent(paciente))
        .addGap(18, 18, 18)
        .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane2)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(cat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(imprimirreposo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(salirreposo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
        .addComponent(Leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    add(cat1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void motivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motivoKeyTyped
        // TODO add your handling code here:
        this.validarcampo(evt);
        if(this.getMotivo().getText().length() >= 200)
        {
            evt.consume();
        }
    }//GEN-LAST:event_motivoKeyTyped
    private void validarcampo(KeyEvent e){
     char b = e.getKeyChar();
         if(!Character.isLetter(b)  &&  b != KeyEvent.VK_SPACE){
            e.consume();
         }
    }
    private void detalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detalleKeyTyped
        this.validarcampo(evt);
        if(this.getMotivo().getText().length() >= 200)
        {
            evt.consume();
        }
    }//GEN-LAST:event_detalleKeyTyped

    private void nrodiasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nrodiasStateChanged
       int num = getNrodias().getComponentCount();
       if(num < 0 || num > 7){
           getNrodias().setValue(getNrodias().getValue());
       }
    }//GEN-LAST:event_nrodiasStateChanged

    private void salirreposoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirreposoActionPerformed
     this.dispose();
    }//GEN-LAST:event_salirreposoActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Leyenda;
  private org.edisoncor.gui.panel.Panel cat1;
  private javax.swing.JTextArea detalle;
  private javax.swing.JButton imprimirreposo;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea motivo;
  private javax.swing.JSpinner nrodias;
  private javax.swing.JLabel nroreposo;
  private javax.swing.JLabel paciente;
  private org.edisoncor.gui.panel.Panel panel2;
  private javax.swing.JButton salirreposo;
  private javax.swing.JLabel sdfsdf;
  // End of variables declaration//GEN-END:variables

}
