/*
 * The MIT License
 *
 * Copyright 2017 Jnatn'h.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package Vista;


import Controlador.ControladorRespaldo;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;

/**
 *
 * @author Jnatn'h
 */
public class Respaldo extends java.awt.Dialog {

    private ControladorRespaldo controller;
    
    public void setController(ControladorRespaldo controller){
        this.controller = controller;
        asignarListener();
    }
    public ControladorRespaldo getController(){
        return this.controller;
    }
    private void asignarListener(){
        Ruta.addActionListener(controller);
        btnDerecha.addActionListener(controller);
        btnIzquierda.addActionListener(controller);
        btnRespaldar.addActionListener(controller);
        btnRestaurar.addActionListener(controller);
        Salir.addActionListener(controller);
        Parcial.addActionListener(controller);
        Total.addActionListener(controller);

        radioSql.addActionListener(controller);
        radioBackup.addActionListener(controller);
    }
    public void setTiporespaldo(ButtonGroup  tiresp){
        this.tipoRespaldo = tiresp;
    }
    public ButtonGroup getTiporespaldo(){
        return this.tipoRespaldo;
    }
    public JButton getBtnDerecha() {
        return btnDerecha;
    }

    public JButton getBtnIzquierda() {
        return btnIzquierda;
    }

    public JButton getBtnRutaSource() {
        return Ruta;
    }

    public ButtonGroup getFormatoSalida() {
        return formatoSalida;
    }

    public JLabel getLabelSource() {
        return labelSource;
    }

    public JList getListadoRespaldar() {
        return listadoRespaldar;
    }

    public JList getListadoTablas() {
        return listadoTablas;
    }

    public JRadioButton getRadioBackup() {
        return radioBackup;
    }

    public JRadioButton getRadioParcial() {
        return Parcial;
    }

    public JRadioButton getRadioSql() {
        return radioSql;
    }

    public JRadioButton getRadioTotal() {
        return Total;
    }

    public JLabel getLabelSO() {
        return labelSO;
    }

    public JButton getBtnRespaldar() {
        return btnRespaldar;
    }

    public JButton getBtnRestaurar() {
        return btnRestaurar;
    }

    public ButtonGroup getTipoRespaldo() {
        return tipoRespaldo;
    }
    public void setLeyenda(JLabel leyenda){
        this.Leyenda = leyenda;
    }
    public JLabel getLeyenda(){
        return this.Leyenda;
    }
    public void setSalir(JButton Salir){
        this.Salir = Salir;
    }
    public JButton getSalir(){
        return this.Salir;
    }
    /**
     * Creates new form Respaldo
     * @param parent una contenedor de primer nivel como lo es Frame. 
     * @param modal si queremos que sea modal o no ... 
     */
    public Respaldo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setController(new ControladorRespaldo(this));
        setModal(modal);
        setResizable(false);
        setTitle("Respaldo de BD");
        centraVentana();
    }
    private void centraVentana(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tipoRespaldo = new javax.swing.ButtonGroup();
    formatoSalida = new javax.swing.ButtonGroup();
    panel = new org.edisoncor.gui.panel.Panel();
    panel1 = new org.edisoncor.gui.panel.Panel();
    Leyenda = new javax.swing.JLabel();
    Total = new javax.swing.JRadioButton();
    Parcial = new javax.swing.JRadioButton();
    jLabel1 = new javax.swing.JLabel();
    labelSource = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    radioBackup = new javax.swing.JRadioButton();
    radioSql = new javax.swing.JRadioButton();
    jLabel3 = new javax.swing.JLabel();
    labelSO = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    Ruta = new javax.swing.JButton();
    btnRespaldar = new javax.swing.JButton();
    btnRestaurar = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    listadoTablas = new javax.swing.JList();
    jScrollPane1 = new javax.swing.JScrollPane();
    listadoRespaldar = new javax.swing.JList();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    Salir = new javax.swing.JButton();
    btnDerecha = new javax.swing.JButton();
    btnIzquierda = new javax.swing.JButton();

    setMaximumSize(new java.awt.Dimension(777, 630));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/fondo-registros.png"))); // NOI18N
    panel.setMaximumSize(new java.awt.Dimension(777, 630));
    panel.setPreferredSize(new java.awt.Dimension(777, 630));
    panel.setRequestFocusEnabled(false);

    panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/header-respaldo.png"))); // NOI18N
    panel1.setMaximumSize(new java.awt.Dimension(780, 75));
    panel1.setName(""); // NOI18N
    panel1.setPreferredSize(new java.awt.Dimension(780, 75));

    javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
    panel1.setLayout(panel1Layout);
    panel1Layout.setHorizontalGroup(
      panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panel1Layout.setVerticalGroup(
      panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 75, Short.MAX_VALUE)
    );

    Leyenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    Leyenda.setForeground(new java.awt.Color(254, 254, 254));

    tipoRespaldo.add(Total);
    Total.setForeground(new java.awt.Color(255, 255, 255));
    Total.setText("Total");
    Total.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        TotalFocusGained(evt);
      }
    });

    tipoRespaldo.add(Parcial);
    Parcial.setForeground(new java.awt.Color(255, 255, 255));
    Parcial.setText("Parcial");
    Parcial.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        ParcialFocusGained(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Tipo de respaldo:");

    labelSource.setForeground(new java.awt.Color(255, 255, 255));
    labelSource.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Guardar en:");

    formatoSalida.add(radioBackup);
    radioBackup.setForeground(new java.awt.Color(255, 255, 255));
    radioBackup.setText(".backup");
    radioBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    radioBackup.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        radioBackupFocusGained(evt);
      }
    });

    formatoSalida.add(radioSql);
    radioSql.setForeground(new java.awt.Color(255, 255, 255));
    radioSql.setText(".sql");
    radioSql.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    radioSql.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        radioSqlFocusGained(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Formato Salida:");

    labelSO.setForeground(new java.awt.Color(255, 255, 255));
    labelSO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Sistema operativo:");

    Ruta.setText("...");
    Ruta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Ruta.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        RutaFocusGained(evt);
      }
    });

    btnRespaldar.setForeground(new java.awt.Color(0, 0, 0));
    btnRespaldar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/Floppy-Small-icon.png"))); // NOI18N
    btnRespaldar.setText("Respaldar");
    btnRespaldar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnRespaldar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRespaldar.setIconTextGap(10);
    btnRespaldar.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        btnRespaldarFocusGained(evt);
      }
    });

    btnRestaurar.setForeground(new java.awt.Color(0, 0, 0));
    btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/restaurar base dato.png"))); // NOI18N
    btnRestaurar.setText("Restaurar");
    btnRestaurar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRestaurar.setIconTextGap(10);
    btnRestaurar.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        btnRestaurarFocusGained(evt);
      }
    });

    listadoTablas.setBackground(new java.awt.Color(222, 185, 186));
    listadoTablas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    listadoTablas.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        listadoTablasFocusGained(evt);
      }
    });
    jScrollPane2.setViewportView(listadoTablas);

    listadoRespaldar.setBackground(new java.awt.Color(202, 228, 201));
    listadoRespaldar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    listadoRespaldar.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        listadoRespaldarFocusGained(evt);
      }
    });
    jScrollPane1.setViewportView(listadoRespaldar);

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Seleccione las tablas a ...");

    jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Respaldar");

    Salir.setForeground(new java.awt.Color(0, 0, 0));
    Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/salir1.1.png"))); // NOI18N
    Salir.setText("Salir");
    Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Salir.setIconTextGap(10);

    btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/der.png"))); // NOI18N
    btnDerecha.setBorder(null);
    btnDerecha.setBorderPainted(false);
    btnDerecha.setContentAreaFilled(false);
    btnDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnDerecha.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        btnDerechaFocusGained(evt);
      }
    });

    btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagen/izq.png"))); // NOI18N
    btnIzquierda.setBorder(null);
    btnIzquierda.setBorderPainted(false);
    btnIzquierda.setContentAreaFilled(false);
    btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnIzquierda.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        btnIzquierdaFocusGained(evt);
      }
    });

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel1)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelLayout.createSequentialGroup()
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(labelSource, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                  .addGroup(panelLayout.createSequentialGroup()
                    .addComponent(Parcial)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Total))
                  .addGroup(panelLayout.createSequentialGroup()
                    .addComponent(radioSql)
                    .addGap(12, 12, 12)
                    .addComponent(radioBackup))
                  .addComponent(labelSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ruta))
              .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(panelLayout.createSequentialGroup()
                .addComponent(btnRespaldar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(btnDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel6)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(77, 77, 77))))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(Leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
      .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
    );
    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Parcial)
          .addComponent(Total)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelSource, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radioSql)
            .addComponent(radioBackup))
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(labelSO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(jLabel6))
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(panelLayout.createSequentialGroup()
            .addGap(94, 94, 94)
            .addComponent(btnDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28))
          .addGroup(panelLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnRespaldar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addComponent(Leyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    add(panel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void ParcialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ParcialFocusGained
        String leyenda = "Seleccione parcial solo si no va a respaldar todas las tablas";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_ParcialFocusGained

    private void TotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TotalFocusGained
        String leyenda = "Respaldo total de la base de dato";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_TotalFocusGained

    private void radioSqlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radioSqlFocusGained
        String leyenda = "Salida en formato SQl";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_radioSqlFocusGained

    private void radioBackupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radioBackupFocusGained
        String leyenda = "Salida en formato Backup";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_radioBackupFocusGained

    private void RutaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RutaFocusGained
        String leyenda = "Seleccione la ruta de salida del archivo";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_RutaFocusGained

    private void listadoTablasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listadoTablasFocusGained
        String leyenda = "Seleccione las tablas que necesite respaldar";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_listadoTablasFocusGained

    private void listadoRespaldarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listadoRespaldarFocusGained
        String leyenda = "Puede quitar las tablas que no desee respaldar";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_listadoRespaldarFocusGained

    private void btnDerechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDerechaFocusGained
        String leyenda = "Mueve el elemento seleccionado al area de respaldo";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_btnDerechaFocusGained

    private void btnIzquierdaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnIzquierdaFocusGained
        String leyenda = "Quita del área de respaldo.";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_btnIzquierdaFocusGained

    private void btnRespaldarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRespaldarFocusGained
        String leyenda = "Respalde la Bd";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_btnRespaldarFocusGained

    private void btnRestaurarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRestaurarFocusGained
        String leyenda = "Restaure la Base de dato";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_btnRestaurarFocusGained

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JLabel Leyenda;
  private javax.swing.JRadioButton Parcial;
  private javax.swing.JButton Ruta;
  private javax.swing.JButton Salir;
  private javax.swing.JRadioButton Total;
  private javax.swing.JButton btnDerecha;
  private javax.swing.JButton btnIzquierda;
  private javax.swing.JButton btnRespaldar;
  private javax.swing.JButton btnRestaurar;
  private javax.swing.ButtonGroup formatoSalida;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel labelSO;
  private javax.swing.JLabel labelSource;
  private javax.swing.JList listadoRespaldar;
  private javax.swing.JList listadoTablas;
  private org.edisoncor.gui.panel.Panel panel;
  private org.edisoncor.gui.panel.Panel panel1;
  private javax.swing.JRadioButton radioBackup;
  private javax.swing.JRadioButton radioSql;
  private javax.swing.ButtonGroup tipoRespaldo;
  // End of variables declaration//GEN-END:variables
}
